export { personSchema } from './person'
export { organizationSchema } from './organization'
export { professionalServiceSchema } from './professionalService'
export { faqPageSchema, type FAQItem } from './faqPage'
export { breadcrumbSchema, type BreadcrumbItem } from './breadcrumb'
export { articleSchema, type ArticleSchemaInput } from './article'
export { localFinancialServiceSchema, type CitySchemaInput } from './localBusiness'
export { speakableWebPageSchema, type SpeakablePageProps } from './speakable'
export { howToSchema, type HowToStep } from './howTo'
